project_id = "cdyvccecrovyjkabfcnx"

[functions.generate-story]
verify_jwt = false

[functions.generate-story-image]
verify_jwt = false

[functions.narrate-story]
verify_jwt = false

[functions.generate-ending]
verify_jwt = false
