/**
 * Visual descriptions for Location settings
 * Used to augment AI image generation with accurate environment depictions
 */

export const LOCATION_DESCRIPTIONS: Record<string, string> = {
  // Season 3 - Don't Make a Sound
  'Utopia': `A desolate, sun-scorched desert outpost comprised of weathered, single-story structures huddled together against the encroaching dunes. The town feels like a relic of the mid-20th century, forgotten by time and buried under layers of fine, orange sand. The buildings are modest and functional, built from wood and corrugated metal that has rusted and bleached under an unforgiving sun.

In the foreground, a prominent, splintering wooden sign stands tall, bearing the ironically optimistic greeting: "WELCOME TO UTOPIA – POP. 42." Behind it, a "GENERAL STORE" serves as the town's focal point, its porch shaded by a sagging roof. A vintage, dark-red pickup truck—possibly a 1940s Chevy—sits idle and caked in dust in front of the store, looking like it hasn't moved in decades.

The surrounding landscape is an endless sea of rolling sand dunes that ripple toward the horizon. To the left, a massive, ominous plume of dark smoke or sand erupts into the air, as if something gargantuan has just breached the surface. Jagged, dark monoliths—or perhaps the appendages of something far larger—protrude from the sand nearby, casting long, sharp shadows.

To the right, the sky is a brilliant, fiery canvas of deep oranges and reds where the sun is making its final descent. Atop a distant dune, a lone human silhouette stands perfectly still, dwarfed by the scale of the desert and the impending chaos behind them. The contrast between the vibrant sunset and the dark, churning dust cloud creates a sense of immediate, cinematic peril.

The overall atmosphere is one of profound isolation and "last-stand" desperation. It captures the exact moment before a peaceful evening turns into a fight for survival, where the heat of the day is being replaced by a cold, creeping dread. It feels like a frame from a high-stakes 1980s creature feature where the hero realizes they are very much not alone.

Key elements: Arid desert setting with rolling sand dunes and a town buried in dust. Weathered wooden structures including a General Store and modest houses. Ironical "Welcome to Utopia" sign with a low population count. Vintage pickup truck and a lone silhouetted figure. Dramatic sunset sky clashing with a massive, dark eruption or dust cloud. Ominous dark shapes protruding from the desert floor.`,

  // Season 3 - The Marrek Murders
  'Marrek Warehouse': `A massive industrial monolith of rust and corrugated metal that looms over the landscape, appearing less like a functional storage facility and more like a graveyard for heavy industry. The exterior is a patchwork of oxidization and weathered steel, suggesting a structure that has been abandoned by time but remains standing through sheer, stubborn mass.

Inside, the air is thick and heavy, carrying the sharp, metallic scent of hydraulic fluid mixed with centuries of settled dust. The cavernous space is lit by the rhythmic, cold pulse of overhead fluorescent lights. These flickering tubes cast a sickly, intermittent glow, illuminating the constant dance of dust motes in the stagnant air.

The scale of the warehouse is intentionally deceptive. While the ceilings reach into shadow, the floor is a suffocating grid of towering shipping crates and jagged, rusted machinery. This layout creates a dense, claustrophobic labyrinth where every turn feels like a dead end. The shadows here possess a physical weight, pressing in against the failing light and obscuring the true depth of the aisles.

What truly defines the space is its mechanical heartbeat. A constant, low-frequency hum vibrates through the floor, generated by a network of active conveyor belts. This creates an unsettling sense of motion even while standing still—a literal conveyor belt to one's own demise that shifts the ground unpredictably. Intermittent hisses from steam vents and the grinding of hidden gears mask the sound of movement.

There is a terrifying verticality to the environment. Narrow, rusted gantries and catwalks crisscross the upper reaches of the warehouse, offering a bird's-eye view of the industrial carnage below. However, these walkways are often high-altitude traps with crumbling railings and few points of egress, leaving those above exposed and cornered.

The warehouse feels alive and utterly indifferent to its occupants. It is an environment of grinding metal and hissing pressure where the machinery continues its mindless work, ensuring that any approaching footsteps remain unheard until it is far too late to run.

Key elements: Monolithic exterior of rusted corrugated metal and industrial decay. Cavernous interior filled with a suffocating grid of towering crates and jagged machines. Flickering, cold fluorescent lighting that creates rhythmic pulses and deep shadows. Active conveyor belts and hissing steam vents providing constant motion and noise. Elevated, rusted gantries and narrow catwalks creating dangerous verticality. Atmosphere of heavy dust and the scent of hydraulic fluid.`,

  // Season 3 - Hell to Pay
  'Hellscape': `A cavernous, soot-stained industrial foundry defined by heavy iron structures, massive overhead support beams, and a floor of reinforced metal grating. The environment is thick with age and grime, feeling oppressive and sweltering—a place where the scale of the machinery dwarfs the people operating it.

At the center of the scene is a pit of incandescent molten metal, radiating an intense, blinding orange glow that serves as the primary light source. Constant streams of sparks erupt from the liquid fire, swirling around massive, blackened gears and heavy industrial chains that loom over the work area.

Four laborers, clad in heavy, soot-streaked work coats and dark beanies, stand along a rusted safety railing. They lean over the edge with a mix of exhaustion and wary vigilance, their forms silhouetted against the fiery light. Their presence suggests a routine that is as monotonous as it is life-threatening.

The background is a murky expanse of industrial pipes and massive cylindrical machinery, partially obscured by a dense, swirling fog of grey smoke and steam. These elements create a claustrophobic sense of isolation within the vast, dark space, as if the factory extends infinitely into the shadows.

The lighting is high-contrast and dramatic; the fiery brilliance of the molten iron clashes with the deep, ink-black shadows of the surrounding mill. Visibility is limited by the haze, making the environment feel unpredictable and hazardous.

The atmosphere is heavy, hot, and menacing—a landscape of fire and iron where the air feels thick with the smell of sulfur and the constant, rhythmic roar of heavy industry.

Key elements: Cavernous iron foundry with heavy industrial machinery. Central pit of glowing molten metal and flying sparks. Workers in soot-covered gear leaning on a metal railing. Dense haze of steam, smoke, and grime. Dramatic, high-contrast lighting from the liquid fire.`,
  "Camp Happy Trails": `A secluded lakeside summer camp set deep in a forest, composed of small wooden cabins arranged loosely around a central dirt path and communal fire pit. The camp feels modest, old-fashioned, and slightly neglected rather than abandoned—structures are intact but weathered, with peeling wood, uneven steps, and soft yellow light glowing from cabin windows.

At the heart of the camp is a large circular fire pit surrounded by rough-hewn log benches. The fire burns steadily, casting long, flickering shadows across the ground and nearby trees. The firelight creates a false sense of warmth and safety.

A calm lake borders the camp, its surface glassy and reflective, partially obscured by low-lying mist that rolls gently across the water and creeps toward the cabins. The lake reflects cabin lights and trees, doubling the sense of stillness and isolation.

A narrow dirt road leads into the camp, marked by a simple wooden sign reading "Camp Happy Trails." An old mid-century car is parked near the path, hinting at recent arrival or an attempt to leave.

The surrounding forest is dense, dark, and enclosing—tall trees press in close, limiting sightlines and sound. Beyond the firelight, visibility drops off quickly into shadow and fog.

The camp feels quiet, suspended, and watchful—as if something is present but waiting. Key elements: Lakeside setting with visible mist or fog. Small wooden cabins with warm interior light. Central fire pit with log seating. Dense forest enclosing the space. A single access path or dirt road.`,

  "Carnival of Blood": `A derelict traveling carnival frozen in time, set under a storm-heavy sky. The grounds are muddy and uneven, with puddles reflecting strings of warm carnival lights that still glow despite the absence of joy. Everything feels recently active but wrong—like the crowd left in a hurry.

At the center stands a large striped circus tent ("The Big Top"), its fabric sagging slightly with age and moisture. The entrance is lit and open, inviting but ominous, as if something inside is waiting for an audience that never arrived.

Surrounding the big top are decaying attractions: A House of Mirrors with flickering marquee lights. A Ferris wheel looming silently in the background. Rusted animal cages on wagons, doors closed but suggestive. A small ticket booth still staffed or recently abandoned. Old carnival signage, hand-painted and weathered.

The ground is churned mud, suggesting heavy foot traffic followed by rain. Light bulbs glow warmly, contrasting sharply with the cold sky and dark surroundings.

The carnival feels theatrical but rotten—performance stripped of innocence. Key elements: Large striped big top tent at center. Carnival lights glowing despite abandonment. House of Mirrors or funhouse facade. Ferris wheel visible in silhouette. Animal cages or wagons present. Mud, puddles, and stormy skies.`,

  "Maple Lane": `A calm, middle-class suburban neighborhood at dusk or early night, centered on a four-way residential intersection. Modest single-family homes with pitched roofs and tidy lawns line the streets, their porch lights and interior lamps glowing warmly. Everything appears orderly, safe, and routine.

Streetlights cast soft pools of amber light onto damp asphalt, creating reflective patches on the road surface. The streets are empty—no pedestrians, no moving cars—just stillness. The silence feels intentional rather than late.

At the edge of the sidewalk sits a small, unsettling detail: abandoned children's toys—a tricycle, a ball—left near the curb as if dropped mid-play. These objects feel recent, not forgotten.

Leafless trees frame the scene, their bare branches cutting into the deep blue evening sky. The neighborhood stretches outward evenly in all directions, offering no obvious refuge—only repetition.

The location feels watched, paused, and vulnerable. Nothing is visibly wrong, which makes everything feel wrong. Key elements: Four-way residential intersection. Single-family suburban houses with warm lights on. Streetlights illuminating wet pavement. Abandoned children's toys near the curb. Leafless trees and empty streets.`,

  "Wolfe Asylum": `An imposing, Victorian-era psychiatric hospital constructed from weathered, rough-hewn grey stone, set against a bleak and overcast sky. The building, identified by a rusted metal archway as "Wolfe Asylum - Est. 1899," dominates the landscape with its multi-story Gothic architecture, featuring steep gables, narrow windows—some boarded over—and a prominent central arched portico. The left wing is heavily draped in dark green ivy, while the rest of the stone appears soot-stained and neglected.

In the foreground, a pair of rusted, wrought-iron gates stand partially open, leading to a cracked asphalt driveway littered with dead, fallen leaves and overgrown weeds. The surrounding grounds are unkempt, with skeletal trees and wild grass pressing in from the edges, limiting the horizon. A newer, white sign reading "HAVEN" is mounted near the main entrance, creating a jarring, modern contrast against the ancient, forbidding stone walls.

The overall aesthetic is one of stagnant isolation and institutional dread. It feels like a place where time has stopped, carrying the heavy weight of forgotten history and buried secrets.

Massive Gothic stone architecture with multi-story gables and slate roofing. Rusted metal archway and partially open iron gates. Boarded-up windows and ivy-covered stone walls. Unkempt grounds with dead leaves and bare, skeletal trees. Dismal, overcast lighting and a small "HAVEN" sign near the door.`,

  "Sunnydaze Mall": `A bustling two-story indoor shopping mall named "Sunny Daze Mall," characterized by a bright, airy atrium and a mix of niche retail stores overlooking a communal food court. The architecture features clean lines, stark white walls, and a large grid-like skylight that floods the central space with natural light, giving the interior a crisp, midday feel.

The upper level features a glass-railed mezzanine lined with specialty storefronts including "Military Surplus Rus," "Stan's Sporting Goods," and "Boards 'N' Bones." These shops are framed with warm wood paneling and large glass displays, offering a view of the shoppers below. A set of dual escalators serves as the focal point for vertical transit, positioned centrally near the "Atrium" signage.

At the heart of the ground floor is an expansive food court filled with dozens of light-wood tables and chairs. The area is active with people of all ages eating, chatting, and resting between shops. Flanking the seating area are smaller kiosks and service-oriented counters like "Zap Snack," a dedicated "Security" desk, and "Smokin' Subject," while a "Service Entrance" and public restrooms are tucked into the far corner.

The environment feels social and nostalgic—a classic suburban hub captured in a moment of peak weekend activity. The lighting is a blend of cool, natural daylight from the ceiling and the warm, inviting glow of the individual shop interiors, creating a clean and welcoming atmosphere.

Two-story indoor mall with a central atrium and large skylight. Upper-level retail including sporting goods and hobby shops with wood-paneled facades. Ground-level food court with dense communal seating. Functional elements like glass railings, escalators, and security stations. Bright, bustling atmosphere with a diverse crowd of shoppers.`,

  "Shady Acres": `A desolate, sunless rural settlement named "Shady Acres" (Population 412), consisting of a few weathered buildings clustered at a dirt road intersection. The town feels stuck in time and slowly decaying, surrounded on all sides by towering, dried-out cornfields that press against the structures like an encroaching wall.

Dominating the foreground is a battered metal sign marking the town's entrance, its paint faded and edges rusted. To the right, a wooden bulletin board is plastered with various flyers and posters, their edges curling from dampness and neglect, hinting at a community once active but now silent.

The small main street features a Sheriff's Department and a modest general store, both built from worn wood with peeling paint. Two vintage pickup trucks—one white with a tan stripe and another darker model—are parked haphazardly on the dirt lot out front, though there are no signs of drivers or pedestrians.

The surrounding houses are old-fashioned, two-story clapboard structures with empty, dark windows and sagging porches. The flat horizon is swallowed by the gray, heavy overcast of a leaden sky, which muffles the light and deepens the sense of rural isolation.

The atmosphere is eerily silent and watchful, as if the residents vanished mid-task, leaving only the rustle of dry corn stalks and the looming presence of the empty, weathered buildings.

Flat rural landscape with massive, encroaching dried cornfields. Weathered wooden buildings, including a Sheriff's Department. Prominent "Shady Acres" town sign and a bulletin board with posters. Two vintage pickup trucks parked on a central dirt lot. Heavy, overcast gray sky creating a sense of eerie desolation.`,

  "USS Konrad": `A massive, modular industrial mining vessel, the USS KONRAD, suspended in low orbit above a vast, rust-colored terrestrial planet. The ship is a heavy, rectangular behemoth constructed from weathered and scarred metal plating, showing years of exposure to space-borne debris and industrial soot. It is utilitarian and imposing, designed for function rather than aesthetics, with a "used future" aesthetic characterized by exposed machinery and reinforced hull segments.

Faded corporate logos and registry numbers, including "WEYGAR-YUSTARRY MINING CORP," are stenciled across the ship's weathered flank. Thick, heavy umbilical cables and mechanical docking arms extend from the lower midsection, tethering the ship to a skeletal orbital platform or cargo array. Small, glowing portholes dot the various levels of the superstructure, suggesting a sprawling, pressurized interior.

A harsh, brilliant sun flares from the upper corner, casting long, sharp shadows across the ship's uneven surface and highlighting the gritty texture of the hull. Below the vessel, the curve of the planet glows with a thick, hazy orange atmosphere, its surface appearing desolate and wind-swept. The surrounding space is a deep, cold black, making the massive ship feel like a lonely island of industry in the void.

The scene is framed through the thick, dark casing of a nearby window, placing the viewer inside a neighboring vessel or station. The atmosphere is quiet and heavy, conveying the immense scale and isolation of deep-space corporate operations.

Massive, blocky industrial spaceship in orbit. Weathered, scarred metal hull with corporate branding. Thick umbilical cables connecting to a docking platform. Atmospheric orange planet visible in the background. Harsh sunlight and deep shadows against the void of space.`,

  "Station 2891": `A remote, high-arctic research outpost situated in a vast, frozen wasteland, characterized by a series of low-profile, modular industrial buildings heavily insulated against extreme cold. The station appears utilitarian and high-stakes—structures are wrapped in thick, quilted thermal blankets and reinforced panels, with plumes of steam or exhaust rising from vents into the frigid air.

In the foreground, a weather-beaten metal sign stands partially buried in the snow, clearly marked "STATION 2891 - RESTRICTED AREA," establishing a sense of isolation and military or scientific secrecy. A heavy rope line defines a cleared walkway, cutting through the deep, drifted snow to guide personnel through whiteout conditions.

Two figures in heavy, bright red polar parkas and full winter gear walk away from the station, their faces obscured by hoods and goggles. Their presence suggests a routine of survival and observation in an environment where the sub-zero temperatures are a constant threat.

The landscape is an endless, featureless expanse of white under a flat, pale blue twilight sky. The horizon is barely discernible, blurred by a constant haze of blowing snow and ice crystals. There are no trees or landmarks, only the oppressive, silent scale of the tundra.

The atmosphere is one of profound isolation, clinical cold, and quiet dread—a place where the environment is the primary antagonist and the small outpost is the only thin line of defense against the elements.

Key elements: Arctic or Antarctic tundra setting with heavy snow. Insulated modular research buildings with visible exhaust. Restricted area signage and perimeter rope lines. Personnel in high-visibility red extreme-weather gear. Flat, hazy lighting suggesting a polar day or twilight.`,
  
  // Once Upon a Full Moon
  'Storybook Woods': `A hidden, ancient hamlet nestled deep within a primeval, moss-choked forest. The settlement is composed of several primitive, low-slung hovels with thick, shaggy thatched roofs, constructed from rough-hewn stone and weathered wattle-and-daub. These smaller structures are huddled together along a muddy, root-strewn trail, appearing almost like natural outcroppings of the forest floor itself.

Dominating the background is a larger, two-story timber-framed cottage that feels like the heart of the village. It stands taller and more sturdy than the surrounding huts, with a steep thatched roof and a single window emitting a warm, flickering amber glow. This light provides the only splash of color in an otherwise monochromatic world of greys, greens, and browns, suggesting a flicker of life and safety amidst the gloom.

The atmosphere is heavy and damp, with a thick, cool mist that clings to the ground and weaves through the canopy above. Massive, gnarled trees with sprawling, serpentine roots hem in the clearing, their twisted branches draped in layers of lichen and moss. The forest feels alive and suffocating, as if the trees are slowly reclaiming the space occupied by the small community.

A damp, uneven dirt path winds through the center of the hamlet, pockmarked with shallow puddles and choked by protruding roots. Dilapidated stone walls and piles of dry brush line the way, suggesting a community that lives in precarious harmony with the encroaching wilderness. There are no signs of modern life—no metal, no glass, just the raw materials of the earth.

The village feels timeless and eerie, like a setting from a dark folk tale where the air is thick with the scent of damp earth and woodsmoke. It is a place of guarded seclusion and ancient secrets, where the silence is heavy and the forest seems to be watching.

Key elements: Ancient forest hamlet with primitive, thatched hovels. Central two-story cottage featuring warm, interior amber light. Dense, moss-covered trees with massive, serpentine root systems. Muddy central path with puddles and crumbling stone walls. Heavy atmospheric mist and cool, overcast lighting.`,

  // A Knock at the Door
  'Wingard Cottage': `A cozy, rustic stone and log cabin perched on a rocky shoreline, overlooking a glass-calm lake at dawn. The cabin is small and sturdy, featuring a prominent fieldstone chimney with a gentle wisp of white smoke trailing into the cool, overcast sky. The architecture is traditional and inviting, with cedar-shingle roofing and small, warm-lit windows that suggest a quiet life inside.

In the foreground, a weathered wooden dock extends into the still water, holding an overturned aluminum rowboat that sits ready for a morning paddle. The lake's surface is perfectly reflective, marred only by a thin, ethereal layer of morning mist that clings to the waterline and the distant evergreen silhouettes.

The surrounding environment is a dense, temperate coniferous forest. Ancient, moss-covered trees frame the scene, their branches draped in vibrant green lichen, highlighting the damp, fresh atmosphere of the Pacific Northwest or a similar boreal wilderness. The ground is a mix of rugged grey rock and soft forest floor, emphasizing the cabin's isolation and its harmony with the rugged landscape.

The overall mood is one of profound stillness, solitude, and "hygge"—a sanctuary tucked away from the modern world, where the only sounds are the crackle of a hearth and the soft lap of water against the pier.

Key elements: Isolated lakeside setting with heavy morning mist. Rustic stone and log cabin with a smoking chimney. Wooden dock with an overturned silver rowboat. Moss-draped evergreen forest framing the composition. Still, reflective water doubling the treeline and sky.`,

  // The Falconwood Files
  'Falconwood': `A quiet, mid-century suburban cul-de-sac called Falconwood, where the architecture consists of modest two-story homes with vinyl siding, dark shutters, and neatly manicured lawns. The neighborhood feels settled and routine, frozen in a state of perpetual late-afternoon gloom under a heavy, overcast sky.

At the entrance of the street stands a weathered wooden sign welcoming visitors to Falconwood, established in 1952. Beside it, a towering wooden utility pole supports a single street light that glows with a harsh, flickering orange hue, casting an unnatural warmth onto the damp asphalt even though the sun hasn't fully set.

A vintage wood-paneled station wagon is parked in one of the driveways, its boxy frame and tan paint reinforcing a distinct 1980s suburban vibe. The houses are well-maintained but feel oddly vacant; porch lights are off, and the white garage doors remain tightly shut, suggesting a neighborhood where privacy is paramount and the streets are intentionally empty.

Beyond the manicured lawns, a dense wall of lush green trees presses right up against the back of the properties, creating a sharp boundary between the civilized street and the untamed woods. A chain-link fence topped with warning signs marks a restricted area near the treeline, hinting at a hidden facility or a forgotten boundary just out of reach.

The atmosphere is one of suburban isolation and quiet dread—the kind of stillness that suggests everyone is indoors, watching from behind their shutters, waiting for something to break the silence.

Key elements: Suburban cul-de-sac with 1980s-style homes and manicured lawns. Weathered wooden "Falconwood" entry sign. Vintage wood-paneled station wagon parked in a driveway. Glowing orange street light under a gloomy, overcast sky. Dense forest backdrop with a restricted chain-link fence.`,

  'MegaBGCon': `A massive board game convention center in full swing—or mid-collapse. The space is a cavernous exhibition hall with high industrial ceilings, exposed ductwork, and harsh fluorescent lighting. Rows upon rows of colorful vendor booths stretch into the distance, draped with banners for fictional board game titles and publishers. Folding tables are covered with game components, dice towers, and half-played games. Food court area visible in the background with food truck-style vendors and plastic seating.

The atmosphere should feel like organized chaos tipping into real chaos: some booths are still staffed and lit, others are overturned or abandoned. Scattered swag bags, dropped lanyards, and spilled drinks on the convention floor. Crowds of attendees in nerdy t-shirts and cosplay, some frozen in confusion, others mid-stampede. Overhead PA system speakers visible. Exit signs glowing red at the far ends of the hall.

Shot from a wide angle to capture the scale and density of the space. Bright, garish convention lighting mixed with shadows where overhead bulbs have gone out. VHS grain and slight color distortion. The vibe is "Comic-Con meets slasher film"—colorful and absurd on the surface, deeply wrong underneath.

Key elements: Convention hall with vendor booths and gaming tables. Food court area with food trucks. Crowded hallways and bottleneck exits. Scattered board game components and dice. Convention banners and signage. Cosplaying attendees. PA system speakers. Red exit signs.`
};

/**
 * Get the visual description for a location by name
 * Returns undefined if no description exists
 */
export function getLocationDescription(name: string): string | undefined {
  return LOCATION_DESCRIPTIONS[name];
}
